/**
 * Emits an idempotent migration that upserts sources.json into public.sources.
 *
 * sources.json is the editable catalog; this keeps the database in step without
 * anyone hand-writing INSERT statements. It only ever inserts or updates —
 * never deletes — so a row removed from the catalog stays in the database until
 * you retire it deliberately.
 *
 *   npm run sources:sql            write supabase/migrations/<ts>_sync_sources.sql
 *   npm run sources:sql -- --stdout   print instead of writing
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { REPO_ROOT } from './env.ts';
import { loadCatalog, parseArgs } from './catalog.ts';

const q = (v: string | null): string => (v == null ? 'null' : `'${v.replace(/'/g, "''")}'`);

function build(): string {
  const catalog = loadCatalog();
  const platforms = [...new Set(catalog.map((s) => s.platform))].sort();

  const rows = catalog
    .map((s) => {
      const strategy = JSON.stringify(s.scrape_strategy ?? {});
      return `  (${q(s.name)}, ${q(s.url)}, ${q(s.source_type)}, ${q(s.platform)}, ${q(strategy)}::jsonb, ${s.active}, ${q(s.notes)})`;
    })
    .join(',\n');

  return `-- Generated by \`npm run sources:sql\` from workers/sources.json — edit that file, not this one.
-- ${catalog.length} sources (${catalog.filter((s) => s.active).length} active) across ${platforms.length} platforms.

insert into public.platforms (platform, label) values
${platforms.map((p) => `  (${q(p)}, ${q(p)})`).join(',\n')}
on conflict (platform) do nothing;

insert into public.sources (name, url, source_type, platform, scrape_strategy, active, notes) values
${rows}
on conflict (platform, url) do update set
  name            = excluded.name,
  source_type     = excluded.source_type,
  scrape_strategy = excluded.scrape_strategy,
  active          = excluded.active,
  notes           = excluded.notes;

-- Anything the catalog no longer lists gets parked, not deleted: an earlier
-- seed may have registered a URL under a different platform, and its events
-- should keep their source_id rather than becoming orphans.
update public.sources s set
  active = false,
  notes  = coalesce(s.notes, '') || ' [deactivated: no longer in workers/sources.json]'
where s.active
  and (s.platform, s.url) not in (
${catalog.map((s) => `    (${q(s.platform)}, ${q(s.url)})`).join(',\n')}
  );
`;
}

const args = parseArgs(process.argv.slice(2));
const sql = build();

if (args['stdout']) {
  console.log(sql);
} else {
  const stamp = new Date().toISOString().replace(/[-:T]/g, '').slice(0, 14);
  const path = resolve(REPO_ROOT, 'supabase/migrations', `${stamp}_sync_sources.sql`);
  writeFileSync(path, sql);
  console.log(`wrote ${path}`);
}
